version: "3"
silent: true

vars:
  OUT_NAME: "classreader"
  CHECK_FLAGS: "-strict-style"
  FLAGS: "-out:{{.OUT_NAME}} {{.CHECK_FLAGS}}"
  DEBUG_FLAGS: "-debug" # -use-separate-modules" TODO: is broken for now

tasks:
  default:
    desc: "Builds the project in release mode"
    aliases: [build, release]
    sources:
      - src/**/*.odin
    generates:
      - "{{.OUT_NAME}}{{exeExt}}"
    cmds:
      - odin build src {{.FLAGS}} -o:speed {{.CLI_ARGS}}
  debug:
    desc: "Builds the project in debug mode"
    cmds:
      - odin build src {{.FLAGS}} {{.DEBUG_FLAGS}} {{.CLI_ARGS}}
  run:
    desc: "Runs the project"
    cmds:
      - odin run src {{.FLAGS}} {{.DEBUG_FLAGS}} -- {{.CLI_ARGS}}
  check:
    desc: "Checks the code for errors"
    cmds:
      - odin check src {{.CHECK_FLAGS}}
      - odin check tests {{.CHECK_FLAGS}} -no-entry-point
  test:
    desc: "Executes all tests"
    cmds:
      - odin test tests {{.FLAGS}} {{.DEBUG_FLAGS}}
